#!/usr/bin/python3

import os
import platform # for python_version_tuple()
import sys

from importlib.machinery import PathFinder
from importlib.metadata import DistributionFinder
from pathlib import Path, PurePath

import installer
from installer import install
from installer._core import _process_WHEEL_file
from installer.destinations import SchemeDictionaryDestination
from installer.sources import WheelFile
# Custom pypa installer script.

# Buildroot: clean up before installing. Otherwise pyPA installer will raise an error.
def clean(src, dest):
	scheme = _process_WHEEL_file(src)
	scheme_path = dest.scheme_dict[scheme]
	context = DistributionFinder.Context(
		name=src.distribution,
		path=[scheme_path],
	)
	for path in PathFinder.find_distributions(context=context):
		# path.files is either an iterable, or None
		if path.files is None:
			continue
		for file in path.files:
			file_path = Path(file.locate())
			if file_path.exists():
				file_path.unlink()

def main():
	if 'KABOOM_TOOLCHAIN_SYSROOT' not in os.environ:
		print("-- KABOOM_TOOLCHAIN_SYSROOT is not set.", file=sys.stderr)
		sys.exit(1)

	DESTDIR = os.environ['KABOOM_TOOLCHAIN_SYSROOT']
	if len(DESTDIR) < 1:
		print("-- KABOOM_TOOLCHAIN_SYSROOT is invalid.", file=sys.stderr)
		sys.exit(1)
	if len(sys.argv) < 2:
		print("-- Requires wheel files to install", file=sys.stderr)
		sys.exit(1)

	# Paths
	PYVER = platform.python_version_tuple()
	PYPATH = "python{}.{}".format(PYVER[0], PYVER[1])
	DESTDIR = Path(DESTDIR).resolve()
	SITE_PACKAGES = DESTDIR / "usr" / "lib" / PYPATH / "site-packages"
	INCDIR = DESTDIR / "usr" / "include" / PYPATH
	BINDIR = DESTDIR / "usr" / "bin"

	files = sys.argv[1:]
	for file in files:
		print(f"-- Installing wheel ‘{PurePath(file).name}’ to ‘{SITE_PACKAGES}’ ...", file=sys.stderr)
		dest = SchemeDictionaryDestination(
			{
				"purelib": SITE_PACKAGES,
				"platlib": SITE_PACKAGES,
				"include": INCDIR,
				"scripts": BINDIR,
				"data": DESTDIR / "usr" / "share",
			},
			interpreter="/usr/bin/python3",
			script_kind="posix"
		)
		try:
			with WheelFile.open(file) as f:
				print("-- Cleaning up before installing ...", file=sys.stderr)
				clean(f, dest)
				installer.install(
					source=f,
					destination=dest,
					additional_metadata={}
				)
			print(f"-- Installed wheeh package ‘{PurePath(file).name}’.", file=sys.stderr)
		except Exception as e:
			print(f"-- Failed to install wheel ‘{file}’: {e}.", file=sys.stderr)
			sys.exit(1)

if __name__ == "__main__":
	main()

# vim: ts=8 sw=8 noexpandtab
