#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' if the stage 1 will be cross-compiled.
KABOOM_TARGET_TRIPLE="alpha-kaboom-linux-gnu"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-mieee -mcpu=ev4"
KABOOM_TARGET_CXXFLAGS="-mieee -mcpu=ev4"

# Target C/C++ Preprocessor flags.
# KABOOM_TARGET_CPPFLAGS=""

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Architecture name in the Linux kernel.
KABOOM_TARGET_KERNEL_ARCH=alpha

# Whether to symlink lib64.
# Alpha does not have a lib64 directory.
KABOOM_LINK_LIB64=0

KABOOM_TARGET_ENDIANNESS=little

# OpenSSL target.
# See Configurations/10-main.conf in OpenSSL source tree for details.
# If in doubt, say "linux-generic(32|64) no-asm" here.
KABOOM_TARGET_OPENSSL_TARGET="linux-alpha-gcc"

GCC_TOOLS_DEF__ALPHA=(
	"--enable-languages=c,c++,lto"
	"--disable-default-ssp"
	"--with-cpu=ev4"
)

GCC_STAGE0_DEF__ALPHA=(
	"--enable-languages=c,c++,lto"
	"--disable-default-ssp"
	"--with-cpu=ev4"
)
