#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' if the stage 1 will be cross-compiled.
KABOOM_TARGET_TRIPLE="x86_64-kaboom-linux-gnu"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-march=x86-64 -mtune=znver4"
KABOOM_TARGET_CXXFLAGS="-march=x86-64 -mtune=znver4"

# Target C/C++ Preprocessor flags.
# KABOOM_TARGET_CPPFLAGS="-march=x86-64-v3 -mavx2"

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Whether qemu user emulation is available for this target.
# If QEMU user emulation is available, specify the entry name in
# /proc/sys/fs/binfmt_misc.
KABOOM_BINFMT=qemu-x86_64

# Skip binfmt detection on the specified architecture.
# For example, amd64 machines can run i486 code natively.
# KABOOM_BINFMT_SKIP=

# Architecture name in the Linux kernel.
KABOOM_TARGET_KERNEL_ARCH=x86

# Output of `uname -m` for the target.
KABOOM_TARGET_UNAME_M="x86_64"

# Whether to symlink lib64.
KABOOM_LINK_LIB64=1

# OpenSSL target.
# See Configurations/10-main.conf in OpenSSL source tree for details.
# If in doubt, say "linux-generic(32|64) no-asm" here.
KABOOM_TARGET_OPENSSL_TARGET="linux-x86_64"

KABOOM_TARGET_ENDIANNESS=little

GCC_TOOLS_DEF__AMD64=(
	"--with-arch=x86-64"
	"--with-tune=znver4"
	"--enable-deafult-ssp"
)

GCC_STAGE0_DEF__AMD64=(
	"--with-arch=x86-64"
	"--with-tune=znver4"
	"--enable-deafult-ssp"
)
