#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' if the stage 1 will be cross-compiled.
KABOOM_TARGET_TRIPLE="armv7l-kaboom-linux-gnueabihf"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-march=armv7-a -mtune=cortex-a7 -mfloat-abi=hard"
KABOOM_TARGET_CXXFLAGS="-march=armv7-a -mtune=cortex-a7 -mfloat-abi=hard"

# Target C/C++ Preprocessor flags.
KABOOM_TARGET_CPPFLAGS="-D_LARGEFILE_SOURCE -D_TIME_OFFSET_BITS=64 -D_FILE_OFFSET_BITS=64"

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Whether qemu user emulation is available for this target.
# If QEMU user emulation is available, specify the entry name in
# /proc/sys/fs/binfmt_misc.
KABOOM_BINFMT=qemu-arm

# Skip binfmt detection on the specified architecture.
# For example, amd64 machines can run i486 code natively.
# KABOOM_BINFMT_SKIP=

# Architecture name in the Linux kernel.
KABOOM_TARGET_KERNEL_ARCH=arm

# Whether to symlink lib64.
KABOOM_LINK_LIB64=0

# OpenSSL target.
# NOTE: OpenSSL uses `linux-armv4' across all arm targets.
# Use -march to generate code for other future variants.
KABOOM_TARGET_OPENSSL_TARGET="linux-armv4"

KABOOM_TARGET_ENDIANNESS=little

GCC_TOOLS_DEF__ARMV7HF=(
	"--enable-default-ssp"
	"--with-arch=armv7-a"
	"--with-float=hard"
	"--with-fpu=neon"
)

GCC_STAGE0_DEF__ARMV7HF=(
	"--enable-default-ssp"
	"--with-arch=armv7-a"
	"--with-float=hard"
	"--with-fpu=neon"
)
