#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' if the stage 1 will be cross-compiled.
KABOOM_TARGET_TRIPLE="i486-kaboom-linux-gnu"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-march=i486 -mtune=bonnell"
KABOOM_TARGET_CXXFLAGS="-march=i486 -mtune=bonnell"

# Target C/C++ Preprocessor flags.
KABOOM_TARGET_CPPFLAGS="-D_LARGEFILE_SOURCE -D_TIME_OFFSET_BITS=64 -D_FILE_OFFSET_BITS=64"

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Architecture name in the Linux kernel.
KABOOM_TARGET_KERNEL_ARCH=x86

# Output of `uname -m` for the target.
KABOOM_TARGET_UNAME_M=i486

# OpenSSL target.
# See Configurations/10-main.conf in OpenSSL source tree for details.
# If in doubt, say "linux-generic(32|64) no-asm" here.
KABOOM_TARGET_OPENSSL_TARGET="linux-x86-latomic"

KABOOM_TARGET_ENDIANNESS=little

GCC_TOOLS_DEF__I486=(
	"--with-cpu=i486"
	"--with-tune=bonnell"
	"--enable-default-ssp"
)

GCC_STAGE0_DEF__I486=(
	"--with-cpu=i486"
	"--with-tune=bonnell"
	"--enable-default-ssp"
)
