#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' when cross-compiling binutils and gcc.
KABOOM_TARGET_TRIPLE="ia64-kaboom-linux-gnu"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-mtune=itanium2"
KABOOM_TARGET_CXXFLAGS="-mtune=itanium2"

# Target C/C++ Preprocessor flags.
# KABOOM_TARGET_CPPFLAGS=""

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Whether qemu user emulation is available for this target.
# If QEMU user emulation is available, specify the entry name in
# /proc/sys/fs/binfmt_misc.
# KABOOM_BINFMT=

# Skip binfmt detection on the specified architecture.
# For example, amd64 machines can run i486 code natively.
# KABOOM_BINFMT_SKIP=

# Architecture name in the Linux kernel.
KABOOM_KERNEL_ARCH=ia64

# Whether to symlink lib64.
KABOOM_LINK_LIB64=1

GLIBC_TOOLS_DEF__IA64=(
	"--disable-werror"
)
