#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' if the stage 1 will be cross-compiled.
KABOOM_TARGET_TRIPLE="m68k-kaboom-linux-gnu"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-march=68020 -mtune=68020-60 -mhard-float -malign-int"
KABOOM_TARGET_CXXFLAGS="-march=68020 -mtune=68020-60 -mhard-float -malign-int"

# Target C/C++ Preprocessor flags.
KABOOM_TARGET_CPPFLAGS="-D_LARGEFILE_SOURCE -D_TIME_OFFSET_BITS=64 -D_FILE_OFFSET_BITS=64"

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Architecture name in the Linux kernel.
KABOOM_TARGET_KERNEL_ARCH=m68k

# Output of `uname -m` for the target.
KABOOM_TARGET_UNAME_M=m68k

# OpenSSL target.
# See Configurations/10-main.conf in OpenSSL source tree for details.
# If in doubt, say "linux-generic(32|64) no-asm" here.
KABOOM_TARGET_OPENSSL_TARGET="linux-latomic"

KABOOM_TARGET_ENDIANNESS=big

GCC_TOOLS_DEF__M68K=(
	"--with-cpu=68020"
	"--enable-default-ssp"
)

GCC_STAGE0_DEF__M68K=(
	"--with-cpu=68020"
	"--enable-default-ssp"
	"--enable-languages=c,c++,"
)
