#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' if the stage 1 will be cross-compiled.
KABOOM_TARGET_TRIPLE="mipsisa64r6el-kaboom-linux-gnuabi64"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-march=mips64r6 -mcompact-branches=always"
KABOOM_TARGET_CXXFLAGS="-march=mips64r6 -mcompact-branches=always"

# Target C/C++ Preprocessor flags.
# KABOOM_TARGET_CPPFLAGS="-march=x86-64-v3 -mavx2"

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Architecture name in the Linux kernel.
KABOOM_TARGET_KERNEL_ARCH=mips

# Output of `uname -m` for the target.
KABOOM_TARGET_UNAME_M="mips64"

# Whether to symlink lib64.
KABOOM_LINK_LIB64=1

# OpenSSL target.
# See Configurations/10-main.conf in OpenSSL source tree for details.
# If in doubt, say "linux-generic(32|64) no-asm" here.
KABOOM_TARGET_OPENSSL_TARGET="linux-generic64"

KABOOM_TARGET_ENDIANNESS=little

GCC_TOOLS_DEF__MIPS64R6EL=(
	"--with-arch=mips64r6"
	"--with-compact-branches=always"
	"--with-msa"
	"--with-nan=2008"
	"--with-float=hard"
)

GCC_STAGE0_DEF__MIPS64R6EL=(
	"--with-arch=mips64r6"
	"--with-compact-branches=always"
	"--with-msa"
	"--with-nan=2008"
	"--with-float=hard"
)
