#!/bin/bash

# Target triple. For stage1 environment and cross toolchain, the vendor
# should be 'kaboom'.
# Vendor will be replaced with 'aosc' if the stage 1 will be cross-compiled.
KABOOM_TARGET_TRIPLE="sparc64-kaboom-linux-gnu"

# Target C Compiler flags.
KABOOM_TARGET_CFLAGS="-mcpu=ultrasparc -mvis -m64 -mcmodel=medany -O2 -fno-tree-ch"
KABOOM_TARGET_CXXFLAGS="-mcpu=ultrasparc -mvis -m64 -mcmodel=medany -O2 -fno-tree-ch"

# Target C/C++ Preprocessor flags.
# KABOOM_TARGET_CPPFLAGS=""

# Target C++ compiler flags.
# KABOOM_TARGET_CXXFLAGS="$KABOOM_TGT_CFLAGS"

# Architecture name in the Linux kernel.
KABOOM_TARGET_KERNEL_ARCH=sparc64

# Whether to symlink lib64.
KABOOM_LINK_LIB64=1

# Target endianness.
KABOOM_TARGET_ENDIANNESS=big

# OpenSSL target.
# See Configurations/10-main.conf in OpenSSL source tree for details.
# If in doubt, say "linux-generic(32|64) no-asm" here.
KABOOM_TARGET_OPENSSL_TARGET="linux64-sparcv9"

GCC_TOOLS_DEF__SPARC64=(
	"--disable-default-ssp"
	"--with-cpu=ultrasparc"
)

GCC_STAGE0_DEF__SPARC64=(
	"--disable-default-ssp"
	"--with-cpu=ultrasparc"
	# Either D or libgphobos is not available.
	"--enable-languages=c,c++,lto,ada"
)
